options {
    directory "/var/cache/bind";

    listen-on port 53 { any; };
    listen-on-v6 { none; };

    recursion yes;
    forwarders { 168.63.129.16; };
    forward only;

    allow-transfer { none; };
};
