options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    recursion yes;
    allow-recursion { 0.0.0.0/0; };
    allow-query { 0.0.0.0/0; };

    forwarders { 168.63.129.16; };
    forward only;

    allow-transfer { none; };
    version "not disclosed";
};
