options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    recursion yes;
    allow-recursion { any; };
    allow-query { any; };

    forwarders { 168.63.129.16; };
    forward only;

    allow-transfer { none; };

    max-cache-size 128M;

    version "not disclosed";
    minimal-responses yes;
};
