name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check current Alpine release
        id: check_release
        run: |
          CURRENT_RELEASE=${{ vars.alpine_container_image_version }}
          echo "Alpine Current: $CURRENT_RELEASE"
          
      - name: Get the latest stable Alpine release from Docker Hub
        id: get_latest_release
        run: |
          set -e
          LATEST_RELEASE=$(curl -s https://hub.docker.com/v2/repositories/library/alpine/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$LATEST_RELEASE" ]; then
            echo "Failed to fetch latest Alpine release."
            exit 1
          fi
          echo "Alpine Latest Stable: $LATEST_RELEASE"

      - name: Compare versions and update if necessary
        if: ${{ steps.check_release.outputs.CURRENT_RELEASE }} != ${{ steps.get_latest_release.outputs.LATEST_RELEASE }}
        run: |
          LATEST_VERSION="${{ steps.get_latest_release.outputs.LATEST_RELEASE }}"
          CURRENT_VERSION="${{ steps.check_release.outputs.CURRENT_RELEASE }}"

          echo "debug"
          echo "LATEST: $LATEST_VERSION"
          echo "CURRENT: $CURRENT_VERSION"

          
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Updating Alpine to $LATEST_VERSION"
            # Perform update steps here
          else
            echo "No update needed. Current version is up to date."
          fi
