name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check current Alpine release
        id: check_release
        run: |
          CURRENT_VERSION=${{ vars.alpine_container_image_version }}
          echo "Alpine Current: $CURRENT_VERSION"
          echo CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: echo 
        id: echo_response
        run: | 
          echo yes: $CURRENT_VERSION

          

      
