name: Update Alpine Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  check_alpine_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Alpine Version
        id: extract_alpine_version
        run: |
          # Extract the version from the Dockerfile
          version=$(grep -oP 'FROM alpine:\K[0-9]+\.[0-9]+' docker/Dockerfile)
          echo "Alpine version: $version"
          # Set the version as an output
          echo "alpine_version=$version" >> $GITHUB_ENV
