name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check current Alpine release
        run: |
          CURRENT_VERSION=${{ vars.alpine_container_image_version }}
          echo "Alpine Current: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Get the latest stable Alpine release from Docker Hub
        run: |
          set -e
          LATEST_RELEASE=$(curl -s https://hub.docker.com/v2/repositories/library/alpine/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$LATEST_RELEASE" ]; then
            echo "Failed to fetch latest Alpine release."
            exit 1
          fi
          echo "Alpine Latest Stable: $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Compare current and latest versions
        id: compare_versions
        run: |
          CURRENT_VERSION=${{ env.CURRENT_VERSION }}
          LATEST_RELEASE=${{ env.LATEST_RELEASE }}
          echo "Current version: $CURRENT_VERSION"
          echo "Latest release: $LATEST_RELEASE"
          if [[ "$CURRENT_VERSION" != "$(echo $LATEST_RELEASE | awk -F'.' '{print $1"."$2"."$3-1}')" ]]; then
            echo "::set-output name=update_required::true"
          else
            echo "::set-output name=update_required::false"
          fi

  update_job:
    runs-on: ubuntu-latest
    needs: update_release
    if: ${{ needs.update_release.outputs.update_required == 'true' }}
    steps:
      - name: Update Alpine container
        run: |
           echo "Updates Installing"
        # Add steps to perform the update here
