name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      output1: ${{ steps.current_version.outputs.version }}
      output2: ${{ steps.stable_release.outputs.version }}
    steps:
    - name: Get Current version of Alpine Linux
      id: current_version
      run: |
        echo "version=${{vars.alpine_container_image_version}}" >> "$GITHUB_OUTPUT"
    
    - name: Get Latest version of Alpina Linux
      id: stable_release
      run: |
        latestRelease=$(curl -s https://hub.docker.com/v2/repositories/library/alpine/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        echo Stable Release: $latestRelease
        echo "version=$latestRelease" >> "$GITHUB_OUTPUT"

    - name: Compare Current to Latest Stable
      id: compare_versions
      run: |
        if [ "${{ steps.current_version.outputs.version }}" != "${{ steps.stable_release.outputs.version }}" ]; then
          echo "Versions mismatched, updating..."
          echo "::set-output name=update_required::true"
        else
          echo "Versions matched, no update required."
          echo "::set-output name=update_required::false"
        fi     
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
