name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs: 
  check_alpine_version:
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{steps.get_current_version.output.version}}

    steps:
      - name: Get Current Version 
        id: get_current_version
        run: | 
          echo "Checking Repository Variable"
          echo "version: ${{ vars.alpine_container_image_version }}"
          echo "version=${{ vars.alpine_container_image_version }}" >> GITHUB_OUTPUT
