name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs:
  check_alpine_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check current Alpine release
        run: |
          CURRENT_VERSION="${{ vars.alpine_container_image_version }}"
          echo "Alpine Current: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Get the latest stable Alpine release from Docker Hub
        run: |
          set -e
          LATEST_RELEASE=$(curl -s https://hub.docker.com/v2/repositories/library/alpine/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$LATEST_RELEASE" ]; then
            echo "Failed to fetch latest Alpine release."
            exit 1
          fi
          echo "Alpine Latest Stable: $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Compare current and latest versions
        run: |
          CURRENT_VERSION="$CURRENT_VERSION"
          LATEST_RELEASE="$LATEST_RELEASE"
          echo "Current version: $CURRENT_VERSION"
          echo "Latest release: $LATEST_RELEASE"
          if [[ "$CURRENT_VERSION" != "$(echo $LATEST_RELEASE | awk -F'.' '{print $1"."$2"."$3-1}')" ]]; then
            echo "update_required=true" >> $GITHUB_ENV
          else
            echo "update_required=false" >> $GITHUB_ENV
          fi

  update_job:
    runs-on: ubuntu-latest
    needs: check_alpine_image
    if: ${{ env.update_required == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
        
      - name: Update Alpine container
        run: | 
          echo "Updating Dockerfile"
        # Add steps to perform the update here
