name: Update Alpine Release

on:
  push:
    branches: main 
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:

jobs: 
  check_alpine_version:
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Version 
        run: | 
          echo "Checking Repository Variable"
          echo "version: ${{ vars.alpine_container_image_version }}"
        
